name: CI

on:
  push: ~

jobs:
  init:
    name: "Say hello"
    runs-on: ubuntu-latest
    steps:
      - name: "First step"
        run: | # This is a multiline command
          echo "Hello world"
          echo "Second line"

