name: CI

on:
  push: ~
  workflow_dispatch: # permet de lancer le workflow manuellement

jobs:
  init:
    name: "Say hello"
    runs-on: ubuntu-latest
    steps:
      - name: "checkout"
        uses: actions/checkout@v4

      - name : "setup node"
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: "List files"
        run: ls

      - name : "Install dependencies"
        run: | 
          npm install
          run -v

      - name: "First step"
        run: | # si il y a plusieurs ligne on met un pipe 
          echo "Hello world"
          echo "Second line"

